security:
    providers:
        in_database:
            entity:
                class: App\Entity\User
                property: username
                    
    encoders:
        App\Entity\User:  bcrypt
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            provider: in_database

            guard:
                authenticators:
                    - App\Security\AppCustomAuthenticator
                    
            logout:
                path: app_logout
            # form_login: true
            # https php bin/console cache:clear://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/security, roles: ROLE_ADMIN }